  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/Lab_8_m?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    jpa:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      show-sql: true
      hibernate:
        ddl-auto: update
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy